### ISSUE TITLE
[Dongyi Guo] Request of being a collaborator.

### ISSUE THREAD

**Issue by dongyi-guo** [razi061/KIT506-Assignment1#1]
Hello Sir! Sincere Greetings! 

So sorry to disturb but is there any chance you could add us as a collaborator of this repository? I wanna learn from the code and we can probs work on KIT506 Assignment 3 on this repo's base.

Thank you so much!

Kind Regards,
Dongyi Guo

**Comment by razi061** [comment]
Please accept the collaboration invite.

**Comment by dongyi-guo** [comment]
Thank you sir!!!
